# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from personio_data_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from personio_data_python_sdk.api_response import AsyncGeneratorResponse
from personio_data_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from personio_data_python_sdk import schemas  # noqa: F401

from personio_data_python_sdk.model.absence_periods_response import AbsencePeriodsResponse as AbsencePeriodsResponseSchema

from personio_data_python_sdk.type.absence_periods_response import AbsencePeriodsResponse

from ...api_client import Dictionary
from personio_data_python_sdk.pydantic.absence_periods_response import AbsencePeriodsResponse as AbsencePeriodsResponsePydantic

# Query params
StartDateSchema = schemas.DateSchema
EndDateSchema = schemas.DateSchema
UpdatedFromSchema = schemas.DateSchema
UpdatedToSchema = schemas.DateSchema


class EmployeesSchema(
    schemas.ListSchema
):


    class MetaOapg:
        items = schemas.IntSchema

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, decimal.Decimal, int, ]], typing.List[typing.Union[MetaOapg.items, decimal.Decimal, int, ]]],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'EmployeesSchema':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> MetaOapg.items:
        return super().__getitem__(i)


class LimitSchema(
    schemas.IntSchema
):
    pass


class OffsetSchema(
    schemas.IntSchema
):
    pass
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'start_date': typing.Union[StartDateSchema, str, date, ],
        'end_date': typing.Union[EndDateSchema, str, date, ],
        'updated_from': typing.Union[UpdatedFromSchema, str, date, ],
        'updated_to': typing.Union[UpdatedToSchema, str, date, ],
        'employees[]': typing.Union[EmployeesSchema, list, tuple, ],
        'limit': typing.Union[LimitSchema, decimal.Decimal, int, ],
        'offset': typing.Union[OffsetSchema, decimal.Decimal, int, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_start_date = api_client.QueryParameter(
    name="start_date",
    style=api_client.ParameterStyle.FORM,
    schema=StartDateSchema,
    explode=True,
)
request_query_end_date = api_client.QueryParameter(
    name="end_date",
    style=api_client.ParameterStyle.FORM,
    schema=EndDateSchema,
    explode=True,
)
request_query_updated_from = api_client.QueryParameter(
    name="updated_from",
    style=api_client.ParameterStyle.FORM,
    schema=UpdatedFromSchema,
    explode=True,
)
request_query_updated_to = api_client.QueryParameter(
    name="updated_to",
    style=api_client.ParameterStyle.FORM,
    schema=UpdatedToSchema,
    explode=True,
)
request_query_employees_ = api_client.QueryParameter(
    name="employees[]",
    style=api_client.ParameterStyle.FORM,
    schema=EmployeesSchema,
    explode=True,
)
request_query_limit = api_client.QueryParameter(
    name="limit",
    style=api_client.ParameterStyle.FORM,
    schema=LimitSchema,
    explode=True,
)
request_query_offset = api_client.QueryParameter(
    name="offset",
    style=api_client.ParameterStyle.FORM,
    schema=OffsetSchema,
    explode=True,
)
# Header params
XPersonioPartnerIDSchema = schemas.StrSchema
XPersonioAppIDSchema = schemas.StrSchema
RequestRequiredHeaderParams = typing_extensions.TypedDict(
    'RequestRequiredHeaderParams',
    {
    }
)
RequestOptionalHeaderParams = typing_extensions.TypedDict(
    'RequestOptionalHeaderParams',
    {
        'X-Personio-Partner-ID': typing.Union[XPersonioPartnerIDSchema, str, ],
        'X-Personio-App-ID': typing.Union[XPersonioAppIDSchema, str, ],
    },
    total=False
)


class RequestHeaderParams(RequestRequiredHeaderParams, RequestOptionalHeaderParams):
    pass


request_header_x_personio_partner_id = api_client.HeaderParameter(
    name="X-Personio-Partner-ID",
    style=api_client.ParameterStyle.SIMPLE,
    schema=XPersonioPartnerIDSchema,
)
request_header_x_personio_app_id = api_client.HeaderParameter(
    name="X-Personio-App-ID",
    style=api_client.ParameterStyle.SIMPLE,
    schema=XPersonioAppIDSchema,
)
SchemaFor200ResponseBodyApplicationJson = AbsencePeriodsResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: AbsencePeriodsResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: AbsencePeriodsResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _get_absence_periods_mapped_args(
        self,
        x_personio_partner_id: typing.Optional[str] = None,
        x_personio_app_id: typing.Optional[str] = None,
        start_date: typing.Optional[date] = None,
        end_date: typing.Optional[date] = None,
        updated_from: typing.Optional[date] = None,
        updated_to: typing.Optional[date] = None,
        employees_: typing.Optional[typing.List[int]] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        _header_params = {}
        if start_date is not None:
            _query_params["start_date"] = start_date
        if end_date is not None:
            _query_params["end_date"] = end_date
        if updated_from is not None:
            _query_params["updated_from"] = updated_from
        if updated_to is not None:
            _query_params["updated_to"] = updated_to
        if employees_ is not None:
            _query_params["employees[]"] = employees_
        if limit is not None:
            _query_params["limit"] = limit
        if offset is not None:
            _query_params["offset"] = offset
        if x_personio_partner_id is not None:
            _header_params["X-Personio-Partner-ID"] = x_personio_partner_id
        if x_personio_app_id is not None:
            _header_params["X-Personio-App-ID"] = x_personio_app_id
        args.query = _query_params
        args.header = _header_params
        return args

    async def _aget_absence_periods_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            header_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestHeaderParams, header_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_start_date,
            request_query_end_date,
            request_query_updated_from,
            request_query_updated_to,
            request_query_employees_,
            request_query_limit,
            request_query_offset,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        for parameter in (
            request_header_x_personio_partner_id,
            request_header_x_personio_app_id,
        ):
            parameter_data = header_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _headers.extend(serialized_data)
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/company/time-offs',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _get_absence_periods_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            header_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestHeaderParams, header_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_start_date,
            request_query_end_date,
            request_query_updated_from,
            request_query_updated_to,
            request_query_employees_,
            request_query_limit,
            request_query_offset,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        for parameter in (
            request_header_x_personio_partner_id,
            request_header_x_personio_app_id,
        ):
            parameter_data = header_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _headers.extend(serialized_data)
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/company/time-offs',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GetAbsencePeriodsRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aget_absence_periods(
        self,
        x_personio_partner_id: typing.Optional[str] = None,
        x_personio_app_id: typing.Optional[str] = None,
        start_date: typing.Optional[date] = None,
        end_date: typing.Optional[date] = None,
        updated_from: typing.Optional[date] = None,
        updated_to: typing.Optional[date] = None,
        employees_: typing.Optional[typing.List[int]] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_absence_periods_mapped_args(
            x_personio_partner_id=x_personio_partner_id,
            x_personio_app_id=x_personio_app_id,
            start_date=start_date,
            end_date=end_date,
            updated_from=updated_from,
            updated_to=updated_to,
            employees_=employees_,
            limit=limit,
            offset=offset,
        )
        return await self._aget_absence_periods_oapg(
            query_params=args.query,
            header_params=args.header,
            **kwargs,
        )
    
    def get_absence_periods(
        self,
        x_personio_partner_id: typing.Optional[str] = None,
        x_personio_app_id: typing.Optional[str] = None,
        start_date: typing.Optional[date] = None,
        end_date: typing.Optional[date] = None,
        updated_from: typing.Optional[date] = None,
        updated_to: typing.Optional[date] = None,
        employees_: typing.Optional[typing.List[int]] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_absence_periods_mapped_args(
            x_personio_partner_id=x_personio_partner_id,
            x_personio_app_id=x_personio_app_id,
            start_date=start_date,
            end_date=end_date,
            updated_from=updated_from,
            updated_to=updated_to,
            employees_=employees_,
            limit=limit,
            offset=offset,
        )
        return self._get_absence_periods_oapg(
            query_params=args.query,
            header_params=args.header,
        )

class GetAbsencePeriods(BaseApi):

    async def aget_absence_periods(
        self,
        x_personio_partner_id: typing.Optional[str] = None,
        x_personio_app_id: typing.Optional[str] = None,
        start_date: typing.Optional[date] = None,
        end_date: typing.Optional[date] = None,
        updated_from: typing.Optional[date] = None,
        updated_to: typing.Optional[date] = None,
        employees_: typing.Optional[typing.List[int]] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        validate: bool = False,
        **kwargs,
    ) -> AbsencePeriodsResponsePydantic:
        raw_response = await self.raw.aget_absence_periods(
            x_personio_partner_id=x_personio_partner_id,
            x_personio_app_id=x_personio_app_id,
            start_date=start_date,
            end_date=end_date,
            updated_from=updated_from,
            updated_to=updated_to,
            employees_=employees_,
            limit=limit,
            offset=offset,
            **kwargs,
        )
        if validate:
            return RootModel[AbsencePeriodsResponsePydantic](raw_response.body).root
        return api_client.construct_model_instance(AbsencePeriodsResponsePydantic, raw_response.body)
    
    
    def get_absence_periods(
        self,
        x_personio_partner_id: typing.Optional[str] = None,
        x_personio_app_id: typing.Optional[str] = None,
        start_date: typing.Optional[date] = None,
        end_date: typing.Optional[date] = None,
        updated_from: typing.Optional[date] = None,
        updated_to: typing.Optional[date] = None,
        employees_: typing.Optional[typing.List[int]] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        validate: bool = False,
    ) -> AbsencePeriodsResponsePydantic:
        raw_response = self.raw.get_absence_periods(
            x_personio_partner_id=x_personio_partner_id,
            x_personio_app_id=x_personio_app_id,
            start_date=start_date,
            end_date=end_date,
            updated_from=updated_from,
            updated_to=updated_to,
            employees_=employees_,
            limit=limit,
            offset=offset,
        )
        if validate:
            return RootModel[AbsencePeriodsResponsePydantic](raw_response.body).root
        return api_client.construct_model_instance(AbsencePeriodsResponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        x_personio_partner_id: typing.Optional[str] = None,
        x_personio_app_id: typing.Optional[str] = None,
        start_date: typing.Optional[date] = None,
        end_date: typing.Optional[date] = None,
        updated_from: typing.Optional[date] = None,
        updated_to: typing.Optional[date] = None,
        employees_: typing.Optional[typing.List[int]] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_absence_periods_mapped_args(
            x_personio_partner_id=x_personio_partner_id,
            x_personio_app_id=x_personio_app_id,
            start_date=start_date,
            end_date=end_date,
            updated_from=updated_from,
            updated_to=updated_to,
            employees_=employees_,
            limit=limit,
            offset=offset,
        )
        return await self._aget_absence_periods_oapg(
            query_params=args.query,
            header_params=args.header,
            **kwargs,
        )
    
    def get(
        self,
        x_personio_partner_id: typing.Optional[str] = None,
        x_personio_app_id: typing.Optional[str] = None,
        start_date: typing.Optional[date] = None,
        end_date: typing.Optional[date] = None,
        updated_from: typing.Optional[date] = None,
        updated_to: typing.Optional[date] = None,
        employees_: typing.Optional[typing.List[int]] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_absence_periods_mapped_args(
            x_personio_partner_id=x_personio_partner_id,
            x_personio_app_id=x_personio_app_id,
            start_date=start_date,
            end_date=end_date,
            updated_from=updated_from,
            updated_to=updated_to,
            employees_=employees_,
            limit=limit,
            offset=offset,
        )
        return self._get_absence_periods_oapg(
            query_params=args.query,
            header_params=args.header,
        )

