# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import personio_data_python_sdk
from personio_data_python_sdk.model.projects_create_project_request import ProjectsCreateProjectRequest
from personio_data_python_sdk import configuration


class TestProjectsCreateProjectRequest(unittest.TestCase):
    """ProjectsCreateProjectRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
