# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import personio_data_python_sdk
from personio_data_python_sdk.model.time_off_type_resource_attributes import TimeOffTypeResourceAttributes
from personio_data_python_sdk import configuration


class TestTimeOffTypeResourceAttributes(unittest.TestCase):
    """TimeOffTypeResourceAttributes unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
