# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import personio_data_python_sdk
from personio_data_python_sdk.model.employees_create_employee_request_employee_custom_attributes import EmployeesCreateEmployeeRequestEmployeeCustomAttributes
from personio_data_python_sdk import configuration


class TestEmployeesCreateEmployeeRequestEmployeeCustomAttributes(unittest.TestCase):
    """EmployeesCreateEmployeeRequestEmployeeCustomAttributes unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
