# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import personio_data_python_sdk
from personio_data_python_sdk.model.public_report_items_attributes_items_item_attributes import PublicReportItemsAttributesItemsItemAttributes
from personio_data_python_sdk import configuration


class TestPublicReportItemsAttributesItemsItemAttributes(unittest.TestCase):
    """PublicReportItemsAttributesItemsItemAttributes unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
