# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import personio_data_python_sdk
from personio_data_python_sdk.model.absences_list_time_off_types_response import AbsencesListTimeOffTypesResponse
from personio_data_python_sdk import configuration


class TestAbsencesListTimeOffTypesResponse(unittest.TestCase):
    """AbsencesListTimeOffTypesResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
