# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from personio_data_python_sdk import schemas  # noqa: F401


class HourlyAbsence(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            id = schemas.UUIDSchema
            measurement_unit = schemas.StrSchema
            effective_duration = schemas.IntSchema
        
            @staticmethod
            def employee() -> typing.Type['ShortEmployee']:
                return ShortEmployee
        
            @staticmethod
            def absence_type() -> typing.Type['AbsenceType']:
                return AbsenceType
        
            @staticmethod
            def certificate() -> typing.Type['HourlyAbsenceCertificate']:
                return HourlyAbsenceCertificate
            start = schemas.DateTimeSchema
            
            
            class end(
                schemas.DateTimeBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, datetime, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'end':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            half_day_start = schemas.BoolSchema
            half_day_end = schemas.BoolSchema
            comment = schemas.StrSchema
            origin = schemas.StrSchema
            status = schemas.StrSchema
            timezone = schemas.StrSchema
            created_by = schemas.IntSchema
            created_at = schemas.StrSchema
            updated_at = schemas.StrSchema
            
            
            class approved_at(
                schemas.DateTimeBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, datetime, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'approved_at':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class breakdowns(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['AbsencePeriodBreakdown']:
                        return AbsencePeriodBreakdown
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['AbsencePeriodBreakdown'], typing.List['AbsencePeriodBreakdown']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'breakdowns':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'AbsencePeriodBreakdown':
                    return super().__getitem__(i)
            __annotations__ = {
                "id": id,
                "measurement_unit": measurement_unit,
                "effective_duration": effective_duration,
                "employee": employee,
                "absence_type": absence_type,
                "certificate": certificate,
                "start": start,
                "end": end,
                "half_day_start": half_day_start,
                "half_day_end": half_day_end,
                "comment": comment,
                "origin": origin,
                "status": status,
                "timezone": timezone,
                "created_by": created_by,
                "created_at": created_at,
                "updated_at": updated_at,
                "approved_at": approved_at,
                "breakdowns": breakdowns,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["measurement_unit"]) -> MetaOapg.properties.measurement_unit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["effective_duration"]) -> MetaOapg.properties.effective_duration: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["employee"]) -> 'ShortEmployee': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["absence_type"]) -> 'AbsenceType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["certificate"]) -> 'HourlyAbsenceCertificate': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["start"]) -> MetaOapg.properties.start: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["end"]) -> MetaOapg.properties.end: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["half_day_start"]) -> MetaOapg.properties.half_day_start: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["half_day_end"]) -> MetaOapg.properties.half_day_end: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["comment"]) -> MetaOapg.properties.comment: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["origin"]) -> MetaOapg.properties.origin: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timezone"]) -> MetaOapg.properties.timezone: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created_by"]) -> MetaOapg.properties.created_by: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created_at"]) -> MetaOapg.properties.created_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updated_at"]) -> MetaOapg.properties.updated_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["approved_at"]) -> MetaOapg.properties.approved_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["breakdowns"]) -> MetaOapg.properties.breakdowns: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "measurement_unit", "effective_duration", "employee", "absence_type", "certificate", "start", "end", "half_day_start", "half_day_end", "comment", "origin", "status", "timezone", "created_by", "created_at", "updated_at", "approved_at", "breakdowns", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["measurement_unit"]) -> typing.Union[MetaOapg.properties.measurement_unit, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["effective_duration"]) -> typing.Union[MetaOapg.properties.effective_duration, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["employee"]) -> typing.Union['ShortEmployee', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["absence_type"]) -> typing.Union['AbsenceType', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["certificate"]) -> typing.Union['HourlyAbsenceCertificate', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["start"]) -> typing.Union[MetaOapg.properties.start, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["end"]) -> typing.Union[MetaOapg.properties.end, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["half_day_start"]) -> typing.Union[MetaOapg.properties.half_day_start, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["half_day_end"]) -> typing.Union[MetaOapg.properties.half_day_end, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["comment"]) -> typing.Union[MetaOapg.properties.comment, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["origin"]) -> typing.Union[MetaOapg.properties.origin, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timezone"]) -> typing.Union[MetaOapg.properties.timezone, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created_by"]) -> typing.Union[MetaOapg.properties.created_by, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created_at"]) -> typing.Union[MetaOapg.properties.created_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updated_at"]) -> typing.Union[MetaOapg.properties.updated_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["approved_at"]) -> typing.Union[MetaOapg.properties.approved_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["breakdowns"]) -> typing.Union[MetaOapg.properties.breakdowns, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "measurement_unit", "effective_duration", "employee", "absence_type", "certificate", "start", "end", "half_day_start", "half_day_end", "comment", "origin", "status", "timezone", "created_by", "created_at", "updated_at", "approved_at", "breakdowns", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        id: typing.Union[MetaOapg.properties.id, str, uuid.UUID, schemas.Unset] = schemas.unset,
        measurement_unit: typing.Union[MetaOapg.properties.measurement_unit, str, schemas.Unset] = schemas.unset,
        effective_duration: typing.Union[MetaOapg.properties.effective_duration, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        employee: typing.Union['ShortEmployee', schemas.Unset] = schemas.unset,
        absence_type: typing.Union['AbsenceType', schemas.Unset] = schemas.unset,
        certificate: typing.Union['HourlyAbsenceCertificate', schemas.Unset] = schemas.unset,
        start: typing.Union[MetaOapg.properties.start, str, datetime, schemas.Unset] = schemas.unset,
        end: typing.Union[MetaOapg.properties.end, None, str, datetime, schemas.Unset] = schemas.unset,
        half_day_start: typing.Union[MetaOapg.properties.half_day_start, bool, schemas.Unset] = schemas.unset,
        half_day_end: typing.Union[MetaOapg.properties.half_day_end, bool, schemas.Unset] = schemas.unset,
        comment: typing.Union[MetaOapg.properties.comment, str, schemas.Unset] = schemas.unset,
        origin: typing.Union[MetaOapg.properties.origin, str, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        timezone: typing.Union[MetaOapg.properties.timezone, str, schemas.Unset] = schemas.unset,
        created_by: typing.Union[MetaOapg.properties.created_by, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        created_at: typing.Union[MetaOapg.properties.created_at, str, schemas.Unset] = schemas.unset,
        updated_at: typing.Union[MetaOapg.properties.updated_at, str, schemas.Unset] = schemas.unset,
        approved_at: typing.Union[MetaOapg.properties.approved_at, None, str, datetime, schemas.Unset] = schemas.unset,
        breakdowns: typing.Union[MetaOapg.properties.breakdowns, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'HourlyAbsence':
        return super().__new__(
            cls,
            *args,
            id=id,
            measurement_unit=measurement_unit,
            effective_duration=effective_duration,
            employee=employee,
            absence_type=absence_type,
            certificate=certificate,
            start=start,
            end=end,
            half_day_start=half_day_start,
            half_day_end=half_day_end,
            comment=comment,
            origin=origin,
            status=status,
            timezone=timezone,
            created_by=created_by,
            created_at=created_at,
            updated_at=updated_at,
            approved_at=approved_at,
            breakdowns=breakdowns,
            _configuration=_configuration,
            **kwargs,
        )

from personio_data_python_sdk.model.absence_period_breakdown import AbsencePeriodBreakdown
from personio_data_python_sdk.model.absence_type import AbsenceType
from personio_data_python_sdk.model.hourly_absence_certificate import HourlyAbsenceCertificate
from personio_data_python_sdk.model.short_employee import ShortEmployee
