# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from personio_data_python_sdk import schemas  # noqa: F401


class PerformanceTarget(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            performance_target_id = schemas.StrSchema
            performance_target_value = schemas.StrSchema
            __annotations__ = {
                "performance_target_id": performance_target_id,
                "performance_target_value": performance_target_value,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["performance_target_id"]) -> MetaOapg.properties.performance_target_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["performance_target_value"]) -> MetaOapg.properties.performance_target_value: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["performance_target_id", "performance_target_value", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["performance_target_id"]) -> typing.Union[MetaOapg.properties.performance_target_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["performance_target_value"]) -> typing.Union[MetaOapg.properties.performance_target_value, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["performance_target_id", "performance_target_value", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        performance_target_id: typing.Union[MetaOapg.properties.performance_target_id, str, schemas.Unset] = schemas.unset,
        performance_target_value: typing.Union[MetaOapg.properties.performance_target_value, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PerformanceTarget':
        return super().__new__(
            cls,
            *args,
            performance_target_id=performance_target_id,
            performance_target_value=performance_target_value,
            _configuration=_configuration,
            **kwargs,
        )
