# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from personio_data_python_sdk import schemas  # noqa: F401


class PublicHistoricalReportItemsAttributesItemsItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            employee_id = schemas.IntSchema
        
            @staticmethod
            def historical_attributes() -> typing.Type['PublicHistoricalReportItemsAttributesItemsItemHistoricalAttributes']:
                return PublicHistoricalReportItemsAttributesItemsItemHistoricalAttributes
            __annotations__ = {
                "employee_id": employee_id,
                "historical_attributes": historical_attributes,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["employee_id"]) -> MetaOapg.properties.employee_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["historical_attributes"]) -> 'PublicHistoricalReportItemsAttributesItemsItemHistoricalAttributes': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["employee_id", "historical_attributes", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["employee_id"]) -> typing.Union[MetaOapg.properties.employee_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["historical_attributes"]) -> typing.Union['PublicHistoricalReportItemsAttributesItemsItemHistoricalAttributes', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["employee_id", "historical_attributes", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        employee_id: typing.Union[MetaOapg.properties.employee_id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        historical_attributes: typing.Union['PublicHistoricalReportItemsAttributesItemsItemHistoricalAttributes', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PublicHistoricalReportItemsAttributesItemsItem':
        return super().__new__(
            cls,
            *args,
            employee_id=employee_id,
            historical_attributes=historical_attributes,
            _configuration=_configuration,
            **kwargs,
        )

from personio_data_python_sdk.model.public_historical_report_items_attributes_items_item_historical_attributes import PublicHistoricalReportItemsAttributesItemsItemHistoricalAttributes
