# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class AbsenceOverviewAttribute(BaseModel):
    attribute_id: typing.Optional[str] = Field(None, alias='attribute_id')

    data_type: typing.Optional[Literal["ABSENCE_OVERVIEW"]] = Field(None, alias='data_type')

    start_date: typing.Optional[date] = Field(None, alias='start_date')

    end_date: typing.Optional[date] = Field(None, alias='end_date')

    duration_days: typing.Optional[str] = Field(None, alias='duration_days')

    duration_hours: typing.Optional[str] = Field(None, alias='duration_hours')

    employee_id: typing.Optional[int] = Field(None, alias='employee_id')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
