# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class AttendanceCreateRequestAttendancesItem(BaseModel):
    employee: int = Field(alias='employee')

    date: date = Field(alias='date')

    # Format: hh:mm
    start_time: str = Field(alias='start_time')

    break_: int = Field(alias='break')

    # Format: hh:mm
    end_time: typing.Optional[typing.Optional[str]] = Field(None, alias='end_time')

    comment: typing.Optional[typing.Optional[str]] = Field(None, alias='comment')

    project_id: typing.Optional[typing.Optional[int]] = Field(None, alias='project_id')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
