# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class AttendanceUpdateRequest(BaseModel):
    date: typing.Optional[date] = Field(None, alias='date')

    # Format: hh:mm
    start_time: typing.Optional[str] = Field(None, alias='start_time')

    # Format: hh:mm
    end_time: typing.Optional[typing.Optional[str]] = Field(None, alias='end_time')

    break_: typing.Optional[int] = Field(None, alias='break')

    comment: typing.Optional[typing.Optional[str]] = Field(None, alias='comment')

    project_id: typing.Optional[typing.Optional[int]] = Field(None, alias='project_id')

    # Optional, default value is true. If set to false, the approval status of the attendance period will be \"pending\" if an approval rule is set for the attendances type. The respective approval flow will be triggered.
    skip_approval: typing.Optional[bool] = Field(None, alias='skip_approval')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
