# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class DurationHistoricalAttribute(BaseModel):
    attribute_id: typing.Optional[str] = Field(None, alias='attribute_id')

    data_type: typing.Optional[Literal["DURATION"]] = Field(None, alias='data_type')

    duration: typing.Optional[int] = Field(None, alias='duration')

    employee_id: typing.Optional[int] = Field(None, alias='employee_id')

    effective_date: typing.Optional[str] = Field(None, alias='effective_date')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
