# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class NewAttendancePeriodParametersRequest(BaseModel):
    # Employee identifier
    attendances[][employee]_: int = Field(alias='attendances[][employee]')

    # Attendance date. Format: yyyy-mm-dd
    attendances[][date]_: date = Field(alias='attendances[][date]')

    # Start time. Format: hh:mm
    attendances[][start_time]_: str = Field(alias='attendances[][start_time]')

    # Break in minutes
    attendances[]break_: int = Field(alias='attendances[]break')

    # End time. Format: hh:mm
    attendances[][end_time]_: typing.Optional[typing.Optional[str]] = Field(None, alias='attendances[][end_time]')

    # Optional comment
    attendances[][comment]_: typing.Optional[typing.Optional[str]] = Field(None, alias='attendances[][comment]')

    # Optional, default value is true. If set to false, the approval status of the attendance period will be \"pending\" if an approval rule is set for the attendances type. The respective approval flow will be triggered.
    skip_approval: typing.Optional[bool] = Field(None, alias='skip_approval')

    # The ID of the project
    project_id: typing.Optional[typing.Optional[int]] = Field(None, alias='project_id')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
