# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from personio_data_python_sdk.paths.company_time_offs.post import AddAbsenceData
from personio_data_python_sdk.paths.company_absence_periods.post import AddAbsencePeriodsData
from personio_data_python_sdk.paths.company_time_offs_id.delete import DeleteAbsenceData
from personio_data_python_sdk.paths.company_absence_periods_id.delete import DeletePeriodData
from personio_data_python_sdk.paths.company_time_offs_id.get import GetAbsencePeriod
from personio_data_python_sdk.paths.company_time_offs.get import GetAbsencePeriods
from personio_data_python_sdk.paths.company_absence_periods.get import GetHourlyPeriods
from personio_data_python_sdk.paths.company_time_off_types.get import ListTimeOffTypes
from personio_data_python_sdk.apis.tags.absences_api_raw import AbsencesApiRaw


class AbsencesApi(
    AddAbsenceData,
    AddAbsencePeriodsData,
    DeleteAbsenceData,
    DeletePeriodData,
    GetAbsencePeriod,
    GetAbsencePeriods,
    GetHourlyPeriods,
    ListTimeOffTypes,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AbsencesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AbsencesApiRaw(api_client)
