# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from personio_data_python_sdk.paths.company_attendances.post import CreateMultipleAttendances
from personio_data_python_sdk.paths.company_attendances_id.delete import DeleteData
from personio_data_python_sdk.paths.company_attendances.get import GetList
from personio_data_python_sdk.paths.company_attendances_id.patch import UpdateAttendanceData
from personio_data_python_sdk.apis.tags.attendances_api_raw import AttendancesApiRaw


class AttendancesApi(
    CreateMultipleAttendances,
    DeleteData,
    GetList,
    UpdateAttendanceData,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AttendancesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AttendancesApiRaw(api_client)
