# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from personio_data_python_sdk.paths.company_document_categories.get import GetCategoriesRaw
from personio_data_python_sdk.paths.company_documents.post import UploadForEmployeesRaw


class DocumentsApiRaw(
    GetCategoriesRaw,
    UploadForEmployeesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
