# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from personio_data_python_sdk.paths.company_document_categories.get import GetCategories
from personio_data_python_sdk.paths.company_documents.post import UploadForEmployees
from personio_data_python_sdk.apis.tags.documents_api_raw import DocumentsApiRaw


class DocumentsApi(
    GetCategories,
    UploadForEmployees,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DocumentsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DocumentsApiRaw(api_client)
