# coding: utf-8

# flake8: noqa

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

__version__ = "1.0"

# import ApiClient
from personio_data_python_sdk.api_client import ApiClient

# import Configuration
from personio_data_python_sdk.configuration import Configuration

# import exceptions
from personio_data_python_sdk.exceptions import OpenApiException
from personio_data_python_sdk.exceptions import ApiAttributeError
from personio_data_python_sdk.exceptions import ApiTypeError
from personio_data_python_sdk.exceptions import ApiValueError
from personio_data_python_sdk.exceptions import ApiKeyError
from personio_data_python_sdk.exceptions import ApiException

from personio_data_python_sdk.client import PersonioData
