# coding: utf-8
"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from personio_data_python_sdk.client_custom import ClientCustom
from personio_data_python_sdk.configuration import Configuration
from personio_data_python_sdk.api_client import ApiClient
from personio_data_python_sdk.type_util import copy_signature
from personio_data_python_sdk.apis.tags.absences_api import AbsencesApi
from personio_data_python_sdk.apis.tags.attendances_api import AttendancesApi
from personio_data_python_sdk.apis.tags.custom_reports_api import CustomReportsApi
from personio_data_python_sdk.apis.tags.documents_api import DocumentsApi
from personio_data_python_sdk.apis.tags.employees_api import EmployeesApi
from personio_data_python_sdk.apis.tags.projects_api import ProjectsApi



class PersonioData(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.absences: AbsencesApi = AbsencesApi(api_client)
        self.attendances: AttendancesApi = AttendancesApi(api_client)
        self.custom_reports: CustomReportsApi = CustomReportsApi(api_client)
        self.documents: DocumentsApi = DocumentsApi(api_client)
        self.employees: EmployeesApi = EmployeesApi(api_client)
        self.projects: ProjectsApi = ProjectsApi(api_client)
