# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAbsencePeriodAttribute(TypedDict):
    pass

class OptionalAbsencePeriodAttribute(TypedDict, total=False):
    attribute_id: str

    data_type: str

    start_date: date

    end_date: date

    half_day_at_start: bool

    half_day_at_end: bool

    employee_id: int

class AbsencePeriodAttribute(RequiredAbsencePeriodAttribute, OptionalAbsencePeriodAttribute):
    pass
