# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from personio_data_python_sdk.type.absence_certificate import AbsenceCertificate
from personio_data_python_sdk.type.absence_time_off_type import AbsenceTimeOffType
from personio_data_python_sdk.type.short_employee import ShortEmployee

class RequiredAbsence(TypedDict):
    pass

class OptionalAbsence(TypedDict, total=False):
    id: int

    status: str

    start_date: str

    end_date: str

    days_count: typing.Union[int, float]

    half_day_start: bool

    half_day_end: bool

    time_off_type: AbsenceTimeOffType

    employee: ShortEmployee

    certificate: AbsenceCertificate

    created_at: str

    # API if the origin is api, otherwise returns an admin employee's name who's account is used to create the absence
    created_by: str

    updated_at: str

class Absence(RequiredAbsence, OptionalAbsence):
    pass
