# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


RequiredAttendanceCreateRequestAttendancesItem = TypedDict("RequiredAttendanceCreateRequestAttendancesItem", {
    "employee": int,

    "date": date,

    # Format: hh:mm
    "start_time": str,

    "break": int,
    })

OptionalAttendanceCreateRequestAttendancesItem = TypedDict("OptionalAttendanceCreateRequestAttendancesItem", {
    # Format: hh:mm
    "end_time": typing.Optional[str],

    "comment": typing.Optional[str],

    "project_id": typing.Optional[int],
    }, total=False)

class AttendanceCreateRequestAttendancesItem(RequiredAttendanceCreateRequestAttendancesItem, OptionalAttendanceCreateRequestAttendancesItem):
    pass
