# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCreateAbsencePeriodRequest(TypedDict):
    # Employee identifier
    employee_id: int

    # Time-off type identifier
    time_off_type_id: int

    # Absence start date. Format: yyyy-mm-dd
    start_date: date

    # Absence end date. Format: yyyy-mm-dd
    end_date: date

class OptionalCreateAbsencePeriodRequest(TypedDict, total=False):
    # Absence start time. Format: HH:mm (hours and minutes) and only required if the start_date and end_date are the same (partial-day absence)
    start_time: date

    # Absence end time. Format: HH:mm (hours and minutes) and only required if the start_date and end_date are the same (partial-day absence)
    end_time: date

    # Whether the start date is a half-day off, only considered if the start_date and end_date are not the same (more than one day absence)
    half_day_start: bool

    # Whether the end date is a half-day off, only considered if the start_date and end_date are not the same (more than one day absence)
    half_day_end: bool

    # Optional comment
    comment: str

    # Optional, default value is true. If set to false, the approval status of the absence request will be \"pending\" if an approval rule is set for the absence type in Personio. The respective approval flow will be triggered.
    skip_approval: bool

class CreateAbsencePeriodRequest(RequiredCreateAbsencePeriodRequest, OptionalCreateAbsencePeriodRequest):
    pass
