# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDocumentEmployeeResponseObjectFirstName(TypedDict):
    pass

class OptionalDocumentEmployeeResponseObjectFirstName(TypedDict, total=False):
    label: str

    value: str

    type: str

    universal_id: str

class DocumentEmployeeResponseObjectFirstName(RequiredDocumentEmployeeResponseObjectFirstName, OptionalDocumentEmployeeResponseObjectFirstName):
    pass
