# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


RequiredEmployeesCreateEmployeeRequest1 = TypedDict("RequiredEmployeesCreateEmployeeRequest1", {
    # Employee email
    "employee[email]": str,

    # Employee first name
    "employee[first_name]": str,

    # Employee last name
    "employee[last_name]": str,
    })

OptionalEmployeesCreateEmployeeRequest1 = TypedDict("OptionalEmployeesCreateEmployeeRequest1", {
    # Employee preferred name
    "employee[preferred_name]": str,

    # Employee gender
    "employee[gender]": str,

    # Employee position
    "employee[position]": str,

    # Employee department
    "employee[department]": str,

    # Employee hire date. Format: yyyy-mm-dd
    "employee[hire_date]": date,

    # Employee weekly working hours
    "employee[weekly_working_hours]": typing.Union[int, float],

    # Employee ID of the Supervisor to be assigned. It needs to belong to a current existing employee, otherwise an error will be returned. If not present, no supervisor will be assigned.
    "employee[supervisor_id]": typing.Union[int, float],

    # Employee status
    "employee[status]": str,
    }, total=False)

class EmployeesCreateEmployeeRequest1(RequiredEmployeesCreateEmployeeRequest1, OptionalEmployeesCreateEmployeeRequest1):
    pass
