# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


RequiredNewAttendancePeriodParametersRequest = TypedDict("RequiredNewAttendancePeriodParametersRequest", {
    # Employee identifier
    "attendances[][employee]": int,

    # Attendance date. Format: yyyy-mm-dd
    "attendances[][date]": date,

    # Start time. Format: hh:mm
    "attendances[][start_time]": str,

    # Break in minutes
    "attendances[]break": int,
    })

OptionalNewAttendancePeriodParametersRequest = TypedDict("OptionalNewAttendancePeriodParametersRequest", {
    # End time. Format: hh:mm
    "attendances[][end_time]": typing.Optional[str],

    # Optional comment
    "attendances[][comment]": typing.Optional[str],

    # Optional, default value is true. If set to false, the approval status of the attendance period will be \"pending\" if an approval rule is set for the attendances type. The respective approval flow will be triggered.
    "skip_approval": bool,

    # The ID of the project
    "project_id": typing.Optional[int],
    }, total=False)

class NewAttendancePeriodParametersRequest(RequiredNewAttendancePeriodParametersRequest, OptionalNewAttendancePeriodParametersRequest):
    pass
