# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from personio_data_python_sdk.type.performance_kpi import PerformanceKpi

class RequiredPerformanceTargetKpi(TypedDict):
    pass

class OptionalPerformanceTargetKpi(TypedDict, total=False):
    performance_target_id: str

    performance_kpis: typing.List[PerformanceKpi]

class PerformanceTargetKpi(RequiredPerformanceTargetKpi, OptionalPerformanceTargetKpi):
    pass
