# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPerformanceKpi(TypedDict):
    pass

class OptionalPerformanceKpi(TypedDict, total=False):
    performance_kpi_id: str

    performance_kpi_value: str

class PerformanceKpi(RequiredPerformanceKpi, OptionalPerformanceKpi):
    pass
