# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredProjectsUpdateData404Response(TypedDict):
    pass

class OptionalProjectsUpdateData404Response(TypedDict, total=False):
    success: bool

    message: str

class ProjectsUpdateData404Response(RequiredProjectsUpdateData404Response, OptionalProjectsUpdateData404Response):
    pass
