# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from personio_data_python_sdk.type.public_report_items_attributes_columns import PublicReportItemsAttributesColumns
from personio_data_python_sdk.type.public_report_items_attributes_filters import PublicReportItemsAttributesFilters
from personio_data_python_sdk.type.public_report_items_attributes_items import PublicReportItemsAttributesItems

class RequiredPublicReportItemsAttributes(TypedDict):
    pass

class OptionalPublicReportItemsAttributes(TypedDict, total=False):
    description: str

    id: str

    name: str

    # Report author
    author_first_name: str

    # Report author
    author_last_name: str

    type: str

    status: str

    start_date: datetime

    end_date: datetime

    created_at: datetime

    updated_at: datetime

    data_refreshed_at: datetime

    columns: PublicReportItemsAttributesColumns

    filters: PublicReportItemsAttributesFilters

    period_type: str

    items: PublicReportItemsAttributesItems

class PublicReportItemsAttributes(RequiredPublicReportItemsAttributes, OptionalPublicReportItemsAttributes):
    pass
