# coding: utf-8

"""
    Personnel Data

    API for reading and writing personnel data including data about attendances, absences, documents, etc

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from personio_data_python_sdk.type.short_employee_attributes_email import ShortEmployeeAttributesEmail
from personio_data_python_sdk.type.short_employee_attributes_first_name import ShortEmployeeAttributesFirstName
from personio_data_python_sdk.type.short_employee_attributes_id import ShortEmployeeAttributesId
from personio_data_python_sdk.type.short_employee_attributes_last_name import ShortEmployeeAttributesLastName

class RequiredShortEmployeeAttributes(TypedDict):
    pass

class OptionalShortEmployeeAttributes(TypedDict, total=False):
    id: ShortEmployeeAttributesId

    first_name: ShortEmployeeAttributesFirstName

    last_name: ShortEmployeeAttributesLastName

    email: ShortEmployeeAttributesEmail

class ShortEmployeeAttributes(RequiredShortEmployeeAttributes, OptionalShortEmployeeAttributes):
    pass
